// swift-tools-version: 5.9

/*
   Copyright 2023 natinusala

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

import PackageDescription

let package = Package(
    name: "ScarletUI",
    products: [
        .executable(
            name: "RendererDemo",
            targets: ["RendererDemo"]
        ),
    ],
    dependencies: [],
    targets: [
        /// The ScarletUI renderer.
        /// Currently a binding to Flutter `RenderObject`s.
        .target(
            name: "Renderer",
            dependencies: [
                "FlutterEngine",
                "GLFW",
                "Glad",
                "CRenderer"
            ],
            exclude: ["Host"]
        ),
        .executableTarget(
            name: "RendererDemo",
            dependencies: ["Renderer"]
        ),
        .target(
            name: "CRenderer",
            dependencies: ["GLFW", "CGlad"]
        ),
        // // Host Flutter app generated by `build_host_SYSTEM-ARCH.sh`
        // .systemLibrary(
        //     name: "HostApp",
        //     path: ".build/scarletui_host/libapp"
        // ),
        // External targets
        .systemLibrary(
            name: "FlutterEngine",
            path: "External/FlutterEngine",
            pkgConfig: "libflutter_engine_scarletui"
        ),
        .target(
            name: "CGlad",
            path: "External/CGlad"
        ),
        .target(
            name: "Glad",
            dependencies: ["CGlad"],
            path: "External/Glad"
        ),
        .systemLibrary(name: "GLFW", path: "External/GLFW", pkgConfig: "glfw3"),
    ]
)
