/*
   Copyright 2022 natinusala

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

/// Allows visiting dynamic properties of any element via the ``Element.accept(visitor:)`` method.
/// For end user, the ``accept(visitor:)`` method is typically generated by the ScarletCodegen package plugin.
public protocol ElementVisitor<Visited> {
    associatedtype Visited: Element

    mutating func visitStateProperty<Value>( keyPath: WritableKeyPath<Visited, State<Value>>, on element: inout Visited)
}
