/*
   Copyright 2022 natinusala

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

// Generated by `codegen.py` from `StaticElementNode.gyb`

public struct StaticMakeInput5<Value>: ElementInput where Value: Element {

}

public struct StaticMakeOutput5<Value, E0, E1, E2, E3, E4>: ElementOutput where Value: Element, E0: Element, E1: Element, E2: Element, E3: Element, E4: Element {
    var e0: E0
    var e1: E1
    var e2: E2
    var e3: E3
    var e4: E4
}

/// An element with static edges, aka. always the same amount of edges with the same type.
/// Performs no equality check on the element so its edges will always be updated ("passthrough" element).
public class StaticElementNode5<Value, E0, E1, E2, E3, E4>: ElementNode where Value: Element, E0: Element, E1: Element, E2: Element, E3: Element, E4: Element, Value.Input == StaticMakeInput5<Value>, Value.Output == StaticMakeOutput5<Value, E0, E1, E2, E3, E4> {
    typealias Input = StaticMakeInput5<Value>
    typealias Output = StaticMakeOutput5<Value, E0, E1, E2, E3, E4>

    public weak var parent: (any ElementNode)?
    public var target: Value.Target?
    public var targetCount = 0
    public var attributes = AttributesStash()

    var e0: E0.Node?
    var e1: E1.Node?
    var e2: E2.Node?
    var e3: E3.Node?
    var e4: E4.Node?

    init(making element: Value, in parent: (any ElementNode)?, targetPosition: Int, using context: Context) {
        self.parent = parent

        // Create the target node
        self.target = Value.makeTarget(of: element)

        // Start a first update without comparing (since we update the value with itself)
        let result = self.update(with: element, targetPosition: targetPosition, using: context, initial: true)

        // Attach the target once everything is ready
        self.insertTargetInParent(position: result.targetPosition)
    }

    public func updateEdges(from output: Value.Output?, at targetPosition: Int, using context: Context) -> UpdateResult {
        // Create edges if updating for the first time
        // Otherwise update them

        var totalTargetCount = 0

        // Edge 0
        let e0TargetPosition = targetPosition + totalTargetCount
        let e0TargetCount: Int
        if let e0 = self.e0 {
            e0TargetCount = e0.compareAndUpdate(
                with: output?.e0,
                targetPosition: e0TargetPosition,
                using: context
            ).targetCount
        } else if let output {
            let edge = E0.makeNode(of: output.e0, in: self, targetPosition: e0TargetPosition, using: context)
            self.e0 = edge
            e0TargetCount = edge.targetCount
        } else {
            nilOutputFatalError(for: E0.self)
        }
        totalTargetCount += e0TargetCount

        targetLogger.trace("\(E0.self) returned target count \(e0TargetCount) - Total: \(totalTargetCount)")
        // Edge 1
        let e1TargetPosition = targetPosition + totalTargetCount
        let e1TargetCount: Int
        if let e1 = self.e1 {
            e1TargetCount = e1.compareAndUpdate(
                with: output?.e1,
                targetPosition: e1TargetPosition,
                using: context
            ).targetCount
        } else if let output {
            let edge = E1.makeNode(of: output.e1, in: self, targetPosition: e1TargetPosition, using: context)
            self.e1 = edge
            e1TargetCount = edge.targetCount
        } else {
            nilOutputFatalError(for: E1.self)
        }
        totalTargetCount += e1TargetCount

        targetLogger.trace("\(E1.self) returned target count \(e1TargetCount) - Total: \(totalTargetCount)")
        // Edge 2
        let e2TargetPosition = targetPosition + totalTargetCount
        let e2TargetCount: Int
        if let e2 = self.e2 {
            e2TargetCount = e2.compareAndUpdate(
                with: output?.e2,
                targetPosition: e2TargetPosition,
                using: context
            ).targetCount
        } else if let output {
            let edge = E2.makeNode(of: output.e2, in: self, targetPosition: e2TargetPosition, using: context)
            self.e2 = edge
            e2TargetCount = edge.targetCount
        } else {
            nilOutputFatalError(for: E2.self)
        }
        totalTargetCount += e2TargetCount

        targetLogger.trace("\(E2.self) returned target count \(e2TargetCount) - Total: \(totalTargetCount)")
        // Edge 3
        let e3TargetPosition = targetPosition + totalTargetCount
        let e3TargetCount: Int
        if let e3 = self.e3 {
            e3TargetCount = e3.compareAndUpdate(
                with: output?.e3,
                targetPosition: e3TargetPosition,
                using: context
            ).targetCount
        } else if let output {
            let edge = E3.makeNode(of: output.e3, in: self, targetPosition: e3TargetPosition, using: context)
            self.e3 = edge
            e3TargetCount = edge.targetCount
        } else {
            nilOutputFatalError(for: E3.self)
        }
        totalTargetCount += e3TargetCount

        targetLogger.trace("\(E3.self) returned target count \(e3TargetCount) - Total: \(totalTargetCount)")
        // Edge 4
        let e4TargetPosition = targetPosition + totalTargetCount
        let e4TargetCount: Int
        if let e4 = self.e4 {
            e4TargetCount = e4.compareAndUpdate(
                with: output?.e4,
                targetPosition: e4TargetPosition,
                using: context
            ).targetCount
        } else if let output {
            let edge = E4.makeNode(of: output.e4, in: self, targetPosition: e4TargetPosition, using: context)
            self.e4 = edge
            e4TargetCount = edge.targetCount
        } else {
            nilOutputFatalError(for: E4.self)
        }
        totalTargetCount += e4TargetCount

        targetLogger.trace("\(E4.self) returned target count \(e4TargetCount) - Total: \(totalTargetCount)")

        return UpdateResult(
            targetPosition: targetPosition,
            targetCount: totalTargetCount
        )
    }

    public func make(element: Value) -> Value.Output {
        let input = Input()
        return Value.make(element, input: input)
    }

    public var allEdges: [(any ElementNode)?] {
        return [
            self.e0,
            self.e1,
            self.e2,
            self.e3,
            self.e4,
        ]
    }
}
